CREATE TABLE IF NOT EXISTS Users (
	ID INTEGER PRIMARY KEY,
   	Username TEXT NOT NULL,
	Pass TEXT NOT NULL,
	UNIQUE(Username)
);
CREATE TABLE IF NOT EXISTS Messages (
	ID INTEGER PRIMARY KEY,
	RoomName TEXT NOT NULL,
	Username TEXT,
	MSG TEXT NOT NULL,
	Timestamp DATETIME
);
CREATE TABLE IF NOT EXISTS Rooms (
	ID INTEGER PRIMARY KEY,
	RName TEXT NOT NULL,
	Pass TEXT NOT NULL,
	UNIQUE(RName)
)